name: Build & Test 🧪

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 📦
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies 📂
        run: dotnet restore WebApi

      - name: Restore 🧱
        run: dotnet restore ./ProjectMap.WebApi.sln

      - name: Build 🧱
        run: dotnet build ./ProjectMap.WebApi.sln --configuration Release --no-restore

      - name: Test 🧪
        run: dotnet test ./ProjectMap.WebApi.sln --configuration Release --no-build

      - name: Publish
        run: dotnet publish ./ProjectMap.WebApi.sln --configuration Release -- no-build
  
